//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medix
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public int WorkOrderId { get; set; }
        public string WorkOrderNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual State State { get; set; }
        public virtual Status Status { get; set; }
    }
}
